import { createRequire } from 'node:module';
import { mkdirSync,writeFileSync } from 'node:fs';
const require=createRequire(new URL('../apps/web/package.json',import.meta.url));
const {chromium}=require('@playwright/test');
mkdirSync('docs/evidence/video',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'docs/evidence/video',size:{width:1440,height:1000}}});
const page=await context.newPage();
const times={date:new Date().toISOString(),model:'rule mode; no model inference',timings:[]};
const first=performance.now();await page.goto('http://127.0.0.1:3000');await page.getByRole('button',{name:'新建分析项目'}).waitFor();
times.timings.push({event:'initial UI visible',milliseconds:performance.now()-first});
await page.getByRole('button',{name:'新建分析项目'}).click();
await page.getByRole('button',{name:'销售订单',exact:true}).click();
await page.getByText('720 行').waitFor();
await page.getByRole('button',{name:'生成分析方案'}).click();
await page.locator('.proposal').filter({hasText:'地区 ·'}).waitFor();
const start=performance.now();await page.locator('.proposal').filter({hasText:'地区 ·'}).click();
await page.locator('.chart-preview iframe').waitFor({timeout:120000});
await page.frameLocator('iframe[title="Chart preview"]').locator('.main-svg').first().waitFor({timeout:120000});
times.timings.push({event:'first rendered chart including queue, Python startup and exports',milliseconds:performance.now()-start});
await page.locator('.result-panel').scrollIntoViewIfNeeded();await page.waitForTimeout(1500);
for(const text of ['标题：区域销售表现','改成蓝色','按数值降序','筛选 地区=华东','撤销']){
 const old=await page.locator('.engine-tag').innerText();const before=performance.now();
 await page.getByLabel('Chart edit').fill(text);await page.getByRole('button',{name:'Apply edit'}).click();
 await page.waitForFunction(old=>document.querySelector('.engine-tag')?.textContent!==old,old,{timeout:120000});
 await page.frameLocator('iframe[title="Chart preview"]').locator('.main-svg').first().waitFor({timeout:120000});
 times.timings.push({event:text,milliseconds:performance.now()-before});await page.waitForTimeout(500);
}
const before=performance.now();const href=await page.getByRole('link',{name:'PNG',exact:true}).getAttribute('href');
const response=await page.request.get('http://127.0.0.1:3000'+href);if(!response.ok())throw Error('Export failed');
writeFileSync('docs/evidence/demo-export.png',await response.body());times.timings.push({event:'download already rendered PNG',milliseconds:performance.now()-before});
await page.locator('.chart-preview').scrollIntoViewIfNeeded();
await page.frameLocator('iframe[title="Chart preview"]').locator('.barlayer .point').nth(3).waitFor({timeout:30000});
await page.waitForTimeout(700);
await page.screenshot({path:'docs/evidence/05-chart-viewport.png'});
await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(500);await page.screenshot({path:'docs/evidence/04-final-workbench.png',fullPage:true});
await page.getByRole('button',{name:'版本记录',exact:true}).click();await page.locator('.history-view').scrollIntoViewIfNeeded();await page.waitForTimeout(1200);
await context.close();await browser.close();writeFileSync('docs/evidence/browser-timings.json',JSON.stringify(times,null,2));
console.log(JSON.stringify(times,null,2));
